### PR TITLE
update ioctl for latest libc definition

### LINKED ISSUE #159: compile failure against latest version of libc
libc 0.1.9 was just released, and nix on linux is failing to compile against it:

```bash
Compiling nix v0.3.9 (file:///vagrant/nix-rust)
src/sys/ioctl.rs:204:38: 204:57 error: mismatched types:
 expected `u64`,
    found `i32`
(expected u64,
    found i32) [E0308]
src/sys/ioctl.rs:204     convert_ioctl_res(libc_ioctl(fd, op as os_ioctl_op_t, data_ptr))
                                                          ^~~~~~~~~~~~~~~~~~~
src/sys/ioctl.rs:204:38: 204:57 help: run `rustc --explain E0308` to see a detailed explanation
src/sys/ioctl.rs:216:38: 216:57 error: mismatched types:
 expected `u64`,
    found `i32`
(expected u64,
    found i32) [E0308]
src/sys/ioctl.rs:216     convert_ioctl_res(libc_ioctl(fd, op as os_ioctl_op_t, data as *const T))
                                                          ^~~~~~~~~~~~~~~~~~~
src/sys/ioctl.rs:216:38: 216:57 help: run `rustc --explain E0308` to see a detailed explanation
src/sys/ioctl.rs:223:47: 223:66 error: mismatched types:
 expected `u64`,
    found `i32`
(expected u64,
    found i32) [E0308]
src/sys/ioctl.rs:223     convert_ioctl_res(unsafe { libc_ioctl(fd, op as os_ioctl_op_t) })
                                                                   ^~~~~~~~~~~~~~~~~~~
src/sys/ioctl.rs:223:47: 223:66 help: run `rustc --explain E0308` to see a detailed explanation
error: aborting due to 3 previous errors
Could not compile `nix`.
```

### PR DESCRIPTION
**Pull request by danburkert**
fixes #159

### CODE REVIEW

**Comment by dpc** [comment]
Worked for me. Thanks.

**Comment by jnicholls** [comment]
Bump. This is important and breaking on latest libc 0.1.9 and nix 0.3.9

**Comment by carllerche** [comment]
Is this still an issue w/ libc 0.1.9 yanked?

**Comment by carllerche** [comment]
The PR is not compatible w/ 0.1.8, so I guess we will need to wait for libc 0.2.0.

**Comment by carllerche** [comment]
I'm going to close this for now in an effort to try to keep things clean.

**Comment by jnicholls** [comment]
We need to do something here though, as we are currently broken.  Either we update nix to have `libc = "0.1.9"` plus the contents of this PR, or we update it to have `libc = "= 0.1.8"` and leave it be.  What would you prefer?

**Comment by carllerche** [comment]
@jnicholls libc 0.1.9 was yanked. It will probably be re-released as 0.2.0 which should avoid the breakage that we saw.

**Comment by jnicholls** [comment]
Ah awesome.  Good call by them.  Thanks.

**Pull request closed without merging**
