### PR TITLE
Add support for preadv and pwritev to sys/uio.

### PR DESCRIPTION
**Pull request by tripped**
Just added the ffi bindings, public wrappers, and a couple of simple tests.

### CODE REVIEW

**Comment by tripped** [comment]
Hah, oopsie, looks like OSX doesn't have preadv and pwritev. Will update.

**Comment by carllerche** [comment]
Sorry for the delay! The tests don't seem to pass on 32 bit linux. Unfortunately, I don't have 32 bit CI setup yet, I just ran it on a virtualbox 32 bit VM.

**Comment by tripped** [comment]
Aha, another oopsie! I'll look into it and fix as soon as I get a chance.

**Comment by carllerche** [comment]
Thanks! Merged: a8182ce667947b33a91e3db03a3688e9f7f565a7

**Pull request closed without merging**
