### PR TITLE
renamed test methods for mqueue and added mq_unlink

### PR DESCRIPTION
**Pull request by MarkusJais**
another function added for posix message queues.

the rest will follow soon.

### CODE REVIEW

**Comment by MarkusJais** [comment]
Currently a strange error with the nightly build:

Compiling nix-test v0.0.1 (file:///Users/travis/build/carllerche/nix-rust)
Build failed, waiting for other jobs to finish...
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'assertion failed: `(left == right)` (left: `'&'`, right: `']'`)', ../src/librustc/metadata/tydecode.rs:567
Could not compile `rand`.
To learn more, run the command again with --verbose.
The command "curl -sSL https://raw.githubusercontent.com/carllerche/travis-rust-matrix/master/test | RUST_TEST_THREADS=1 bash" exited with 1.
4.00s$ cargo doc --no-deps
   Compiling libc v0.1.8
   Compiling bitflags v0.1.1
   Compiling nix v0.3.9 (file:///Users/travis/build/carllerche/nix-rust)
The command "cargo doc --no-deps" exited with 0.


it says "this is a bug." 
strange. maybe temporary

**Comment by MarkusJais** [comment]
Has anybody seen similar errors? I cannot reproduce this. Sometimes it builds, sometimes the compiler seems to crash but it doesn't seem to be related to the mq code.

**Comment by carllerche** [comment]
There have been some intermittent failures. I haven't done much work trying to track them down. I will try to look into it a bit tonight.

**Comment by MarkusJais** [comment]
It looks like both rand and rust-nightly are slightly out of data. Maybe this is fixed with the latest versions. 
On the other hand it says that it's a compiler bug. No activity on the ticket I opened so far.

**Comment by carllerche** [comment]
I'm trying a rebuild.

**Comment by carllerche** [comment]
Looks like the build passes now.

**Comment by carllerche** [comment]
Thanks! Merged: bd265fd8f47142e565294258abb95223f195e96d

**Comment by MarkusJais** [comment]
Thanks for merging. Will be adding the missing functions soon.

**Pull request closed without merging**
