### PR TITLE
basic support for Posix Message Queues

### PR DESCRIPTION
**Pull request by MarkusJais**
I've updated my code a bit and have now created a pull request.

Basic sending of messages works. 

Not all Posix APIs yet implemented.

### CODE REVIEW

**Comment by carllerche** [comment]
Hey there. I tried merging this but it looks like the tests didn't pass. Could you rebase off of master and see what's going on with the tests? Thanks :smile:

**Comment by MarkusJais** [comment]
Did the rebase. According to Travis "All is well" now :-)

**Comment by carllerche** [comment]
I did a little bit of cleanup: https://github.com/carllerche/nix-rust/commit/8127b4dd6d37ae028a31c013b7d5758d66362b04

If that commit looks good, I can push it to master.

**Comment by MarkusJais** [comment]
Looking good!

**Comment by carllerche** [comment]
Merged. Thanks: 8127b4dd6d37ae028a31c013b7d5758d66362b04

**Pull request closed without merging**
