### PR TITLE
iOS: term support is really redundant

### PR DESCRIPTION
**Pull request by vhbit**

### CODE REVIEW

**Comment by carllerche** [comment]
I believe it, but I am no expert here. @utkarshkukreti did the original work. What do you think?

**Comment by utkarshkukreti** [comment]
Are these headers/functions not present in iOS? (I also know next to nothing about iOS..)

**Comment by vhbit** [comment]
They might be presented as iOS shares a lot with OS X. But the main thing is that there is no official way to write and run apps which use term - apps are sandboxed and are GUI-only. The only workaround is to jailbreak device. 

I bet a person who jailbreaks device and runs term apps written in Rust on it, will have enough expertise to open another PR.

**Comment by utkarshkukreti** [comment]
Sounds good. :+1:

**Comment by carllerche** [comment]
Pushed, thanks 19f3690627c45ab91ca849d1cb0c9781716c4367

**Pull request closed without merging**
