### PR TITLE
Bring back mount

### PR DESCRIPTION
**Pull request by kamalmarhubi**
Fixes https://github.com/carllerche/nix-rust/issues/85

### CODE REVIEW

**Comment by kamalmarhubi** [comment]
(Rebased)

**Comment by carllerche** [comment]
Hmmm... it doesn't seem to pass CI. Unsure why.

**Comment by kamalmarhubi** [comment]
Nightly I think is some nightly weirdness. 1.1.0 is because the test is using `Result::expect()`, which was added in 1.4.0. I'll update it to use `unwrap()` or `unwrap_or_else()` given the desire to test on 1.3.0.

**Comment by kamalmarhubi** [comment]
@carllerche I've bashed Travis into submission*. Please check the test to see if what's going on makes sense. Thanks!

* well, Travis forced me to disable one of the tests in CI, but we'll make do.

**Comment by carllerche** [comment]
Instead of re-implementing the test runner, is it possible to use `Once` (call once) construct to do initialization?

**Comment by kamalmarhubi** [comment]
Sadly not. The `unshare` call must happen before any threads are spawned. The built-in runner does not have any way to get code to run before that.

**Comment by kamalmarhubi** [comment]
Other alternatives involve doing weird things with fork / exec and exit statuses to communicate success or failure to the runner.

**Comment by kamalmarhubi** [comment]
@carllerche ping for comments on the test runner

**Comment by kamalmarhubi** [comment]
I'll merge this soon, leaving the "test runner" as is. I filed https://github.com/carllerche/nix-rust/issues/248 to track its improvement.

**Pull request merged**
