### PR TITLE
Support Android on ARM

### PR DESCRIPTION
**Pull request by kennytm**
Note: I have only tested to ensure all test cases in `nix` and `mio` works on Android 4.4 with ARM after this change. Other APIs not covered are not tested.

### CODE REVIEW

**Comment by carllerche** [comment]
Looks good, do you know if there is a way to setup CI for this environment?

**Comment by carllerche** [comment]
I merged here: c5bc33200c8eb3563784c0e18dc37060049247cd but I would like to try to get CI somehow :)

**Comment by carllerche** [comment]
I filed an issue w/ Travis https://github.com/travis-ci/travis-ci/issues/3376

**Comment by kennytm** [comment]
Thanks. 

Travis may be able to fix their issue by providing the Android SDK + NDK and Android emulator / Genymotion simulator, but there are also works to do on the Rust side,

1. There is no Rust nightly for arm-linux-androideabi, so the CI will need to get a custom `rustc` somewhere (compiling it directly in Travis is inefficient, it may take hours) ([this may help?](http://internals.rust-lang.org/t/community-supported-build-slaves-for-2nd-tier-platforms/1528))
2. Cargo does not support cross-testing yet (rust-lang/cargo#1411), so we need to manually `adb push` the artifacts to the Android emulator to run them.

**Comment by carllerche** [comment]
Closing in favor of: #97

**Pull request closed without merging**
