### PR TITLE
Compatibility with rust latest

### PR DESCRIPTION
**Pull request by zmack**
Hey, I was trying to get some stuff done with mio on rust head, and just ended up in this sed-yak-shave, hope you can get some use out of it.

The only tricky bit is the clone implementation in UtsName, which i'm still not sure is 100% correct, but at least it gets tests passing.

Anyway, on this particular branch tests are green on today's rust. Hope it helps :smile_cat:

### CODE REVIEW

**Comment by carllerche** [comment]
Yeah, I've been trying to get nix running on Rust beta. I already applied some of these fixes, but haven't yet pushed. I will attempt to get nix running on the latest nightly at least.

**Comment by fhartwig** [comment]
Re: the UtsName issue: apparently the recommended workaround is the one that I've used in  #92

**Comment by zmack** [comment]
@fhartwig hah, nice, i was wondering about that one.

Good discussion on that as well down [here](https://github.com/rust-lang/rust/pull/23860), thanks for pointing me to it.

**Comment by carllerche** [comment]
Thanks for the PR. Master should be fixed for Rust 1.0 Beta. I ended up merging #92

**Pull request closed without merging**
