### PR TITLE
Use `libc::PATH_MAX` in `NixPath::with_nix_path`.

### PR DESCRIPTION
**Pull request by utkarshkukreti**

### CODE REVIEW

**Comment by utkarshkukreti** [comment]
Hmm, apparently `PATH_MAX` is not defined for Linux in the `libc` crate.

**Comment by carllerche** [comment]
noooooo :( The good news is that libc is going to get an overhaul soon (I hope) :)

**Comment by utkarshkukreti** [comment]
My PR to [add PATH_MAX for Linux](https://github.com/rust-lang/rust/pull/28691) was recently merged. We'll have to wait for a new libc crate release.

**Comment by carllerche** [comment]
Has it been released?

**Comment by utkarshkukreti** [comment]
Yes! [All the tests on Travis are passing now.](https://travis-ci.org/carllerche/nix-rust/builds/88058657)

**Comment by carllerche** [comment]
woohoo

**Comment by carllerche** [comment]
Thanks! Merged: 55134d81a3d64b0f0d9fdec39eca312444b921c7

**Pull request closed without merging**
