### PR TITLE
Bug: TCP_NODELAY should be in IPPROTO_TCP level

### PR DESCRIPTION
**Pull request by zonyitoo**

### CODE REVIEW

**Comment by zonyitoo** [comment]
@carllerche Please merge. This is a fatal bug!

**Comment by posborne** [comment]
@zonyitoo Can you rebase and squash.  I think the only commit we want in this PR is https://github.com/zonyitoo/nix-rust/commit/e2cac27a5fa4c926f7a6173ce204c3b7320635e2

Otherwise, LGTM.

**Comment by zonyitoo** [comment]
@posborne Updated.

**Comment by carllerche** [comment]
Thanks! merged: aa0863b0b9b31630159b5a36db694b43b3500bdc

(Sorry for the delay, I've been traveling :smile:)

**Pull request closed without merging**
