### PR TITLE
Fix signature of linux `clone` function

### PR DESCRIPTION
**Pull request by tailhook**
In fact function returns pid of new process (or tid of new thread)

The signature of the function change, but it's only return value changed from returning nothing to `pid_t` so I believe that I believe that the amount of code it may break is low.

On the other hand I don't even understand how to use `clone` that does *not* return id of newly created process (may be useful for threads?)

### CODE REVIEW

**Comment by tailhook** [comment]
@carllerche, any issues with this? The patch is quite trivial.

**Comment by carllerche** [comment]
Sorry, been trying to keep up w/ mio. Looking at this now.

**Comment by carllerche** [comment]
seeeems good.

**Comment by tailhook** [comment]
No problem. Thanks!

**Pull request merged**
