### PR TITLE
Add everything from poll.h.

### PR DESCRIPTION
**Pull request by utkarshkukreti**
(Only OSX and Linux support.)

### CODE REVIEW

**Comment by utkarshkukreti** [comment]
Travis failure seems to be unrelated:

> Compiling bitflags v0.3.3
> /Users/travis/.cargo/registry/src/github.com-88ac128001ac3a9a/bitflags-0.3.3/src/lib.rs:1:1: 1:1 error: the crate `std` has been compiled with rustc 1.7.0-nightly (6e2a64b57 2015-12-30), which is incompatible with this version of rustc [E0514]

**Comment by utkarshkukreti** [comment]
Passing now.

**Comment by carllerche** [comment]
:+1: Looks good. I gave you push access, so feel free to rebase & merge :)

**Comment by kamalmarhubi** [comment]
Hi @utkarshkukreti! Are you planning to merge this? :-)

**Comment by kamalmarhubi** [comment]
Actually I just rebased and merged it.

**Pull request closed without merging**
