### PR TITLE
Add sys::select::FdSet and sys::select::select.

### PR DESCRIPTION
**Pull request by utkarshkukreti**
Looking for feedback on the `FdSet` and `select` API.

(I lifted the constant values from [here](https://github.com/alexcrichton/wait-timeout/blob/9dbe023ddd985746da1e533ae75f1864a186fa21/src/unix/select.rs).)

### CODE REVIEW

**Comment by carllerche** [comment]
Looks OK to me.

**Comment by utkarshkukreti** [comment]
@carllerche yes :)

**Comment by filsmick** [comment]
:+1: 

`select` support would be wonderful.

**Comment by carllerche** [comment]
I'm seeing some issues on CI... I am unsure if they are related to this commit or a another one.

**Comment by carllerche** [comment]
Looks like it is an unrelated commit

**Comment by carllerche** [comment]
Merged: ee9affe12fa216c84eb11cc3169673b55af1bb56

**Pull request closed without merging**
