### PR TITLE
Libc 024

### PR DESCRIPTION
**Pull request by j16r**
This is an attempt to get nix-rust compiling on FreeBSD. It' built on top of marjakm's fork which upgraded libc to 0.2.2.

### CODE REVIEW

**Comment by j16r** [comment]
Unfortunately none of the Travis builds are on FreeBSD and I definitely have `sys::test_socket::test_scm_rights` failing locally. Any tips on how I might add that builder?

**Comment by arthurprs** [comment]
Thank you for that. I'll use your fox meanwhile.

**Comment by j16r** [comment]
What platform are you on @arthurprs ?

**Comment by arthurprs** [comment]
@j16r freebsd 10.2 amd64

**Comment by j16r** [comment]
Weird, I explicitly disabled that line for freebsd in commit 5df11f4. Are you cross compiling? Can you confirm you're building with `target_os` = `freebsd`? I'm building on the same platform and not getting your error, weird.

**Comment by arthurprs** [comment]
It looks like cargo was using an old commit, I added an explicit commit and it now fails with

```
root@:~/Desktop/floki # cargo test
    Updating git repository `https://github.com/j16r/nix-rust.git`
   Compiling nix v0.3.9
   Compiling nix v0.5.0-pre (https://github.com/j16r/nix-rust.git?rev=84d2c24d428a885e8d7500852b8b08714ab48598#84d2c24d)
   Compiling env_logger v0.3.2
   Compiling uuid v0.1.18
   Compiling twox-hash v0.1.1
/root/.cargo/registry/src/github.com-1ecc6299db9ec823/nix-0.3.9/src/unistd.rs:129:9: 129:22 error: unused import, #[deny(unused_imports)] on by default
/root/.cargo/registry/src/github.com-1ecc6299db9ec823/nix-0.3.9/src/unistd.rs:129     use errno::EINVAL;
                                                                                          ^~~~~~~~~~~~~
error: aborting due to previous error
```

**Comment by j16r** [comment]
Looks like you have two references to `nix`, one of them is pulling 0.3.9.

**Comment by arthurprs** [comment]
Oh, I see. It's mio, but I can't find a way to override that.

**Comment by arthurprs** [comment]
Ok I went around it using .cargo/config It looks like your PR is fine :)

mio will need some adjustments before compiling on it though

**Comment by arthurprs** [comment]
@j16r I sent a PR to your fork in order to get mio working properly.

**Comment by j16r** [comment]
@arthurprs legend! I've merged it in.

**Comment by carllerche** [comment]
Thanks! Going to look at this now. Sorry for the delay.

**Comment by carllerche** [comment]
I'm trying to validate Mio working with this before merging.

**Comment by carllerche** [comment]
I am unsure how CI is passing given that it won't compile on my box... `libc::IPV6_ADD_MEMBERSHIP` doesn't seem to exist anymore for OS X (renamed).

**Comment by carllerche** [comment]
Oops, never mind. I was half way through a rebase

**Comment by carllerche** [comment]
Ok, let's see if Mio CI will pass with this: https://github.com/carllerche/mio/pull/343

**Comment by arthurprs** [comment]
I guess we can close this now since pr343 is in

**Comment by carllerche** [comment]
Ah yes. Thanks

**Comment by j16r** [comment]
Hmm, I'm confused. pr343 is on mio. With this closed I'm still unable to use nix-rust on FreeBSD?

**Comment by kamalmarhubi** [comment]
@j16r this was merged in. I'm not sure what incantation @carllerche uses, but it results in him having to close PRs even when they are merged in. You can see the commits on this PR in the github history: https://github.com/carllerche/nix-rust/commits/master

**Comment by j16r** [comment]
Oh, I missed that, thanks.

**Pull request closed without merging**
