### PR TITLE
feat: add execvpe

### PR DESCRIPTION
**Pull request by houqp**

### CODE REVIEW

**Comment by houqp** [comment]
hmm... weird, it passed for beat, but not nightly, i am using the nightly build too.

**Comment by houqp** [comment]
OK, it passed on nightly now without any change...

**Comment by carllerche** [comment]
Looks mostly good. I don't believe that this function is supported on Darwin (and possibly other OSes). Could you guard the API with cfg flags?

**Comment by houqp** [comment]
Good catch, I moved it into linux module now :)

**Comment by carllerche** [comment]
Thanks! merged.

**Pull request merged**
