### PR TITLE
Add support for SO_{RCV,SEND}BUF(FORCE)? sockopts

### PR DESCRIPTION
**Pull request by jedisct1**
This adds support for `SO_RCVBUF`, `SO_SNDBUF` and the forced version on Linux.

### CODE REVIEW

**Comment by kamalmarhubi** [comment]
@carllerche ping for review. I haven't looked at any of the bits of nix that use macros. Of the current collaborators, you have the most recent commits in this area.

**Comment by kamalmarhubi** [comment]
@jedisct1 the build seems to fail on Linux with

```
src/sys/socket/sockopt.rs:18:59: 18:64 error: unresolved name `consts::SO_SENDBUFFORCE` [E0425]

src/sys/socket/sockopt.rs:18                     let res = ffi::setsockopt(fd, $level, $flag,

                                                                                       ^~~~~

src/sys/socket/sockopt.rs:96:9: 96:62 note: in this expansion of setsockopt_impl! (defined in src/sys/socket/sockopt.rs)

src/sys/socket/sockopt.rs:77:9: 77:75 note: in this expansion of sockopt_impl! (defined in src/sys/socket/sockopt.rs)

src/sys/socket/sockopt.rs:168:1: 168:90 note: in this expansion of sockopt_impl! (defined in src/sys/socket/sockopt.rs)

error: aborting due to previous error
```
Eg, https://travis-ci.org/carllerche/nix-rust/jobs/103905228#L306

**Comment by jedisct1** [comment]
Oops, sorry. This has been fixed, and the PR has been updated.

**Comment by kamalmarhubi** [comment]
@jedisct1 could you add a test? I decided to look into how the sockopt stuff works, and think I understand your change now!

**Comment by jedisct1** [comment]
Done!

**Comment by kamalmarhubi** [comment]
Tests are failing on Linux. From reading [`socket(7)`](http://man7.org/linux/man-pages/man7/socket.7.html)I think you'll have to remove the `FORCE` tests because the tests likely don't run with `CAP_NET_ADMIN`.

**Comment by jedisct1** [comment]
Indeed, these require root privileges.

They have been removed. Thanks!

**Comment by kamalmarhubi** [comment]
Great, I'll merge when CI run finishes. Thanks!

**Comment by kamalmarhubi** [comment]
Merged as https://github.com/carllerche/nix-rust/compare/cdb5eac...e04842e

**Comment by kamalmarhubi** [comment]
Thanks!

**Pull request closed without merging**
